# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe7da4443687882f754cf6318aabbecf8ef1c10dd06371cebfb00b43f87bdadca33ad503419cc27bf788459d6e37ea65d0bed59506124843d3895ba68ebe3c1d

test:
  secret_key_base: 37e48a272ec47c10dd91e9071207fed218d8ea94a20680349d7b910998f3c1a15edee1f2b40ab5f3254c8f947f19e85dadf1b37b863445a4bc18bb4404dc72bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
